title: Blog Bibliotheks- und Archivinformatik
author: Shanna
email: shanna.gruetter@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Vorlage f√ºr ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links
# twitter_username: felixlohmeier # DO NOT include the @ character, or else the build will fail!
github_username:  shannarachel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: Tactile
